# Generated by Django 5.2 on 2025-04-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('znacka', models.CharField(max_length=50)),
                ('rok_vyroby', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='zakaznik',
            name='email',
        ),
        migrations.RemoveField(
            model_name='zakaznik',
            name='telefon',
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auta.auto'),
        ),
    ]
